cache:
  mount:
    - node_modules
    - .git
    - public/lib

build:
  main:
    image: mhart/alpine-node:4.5
    commands:
      - npm install
      - node_modules/.bin/gulp test
      - node_modules/.bin/gulp build
      - node_modules/.bin/gulp test:api &
      - node_modules/.bin/gulp test:worker &
      - sleep 10s
      - node_modules/.bin/abao api/raml/api.raml --server http://localhost:3001/api --hookfiles=api/raml/hooks/*.js
    
compose:
  mongo:
    image: newcrossfoodcoop/nxfc-mongo:latest
  redis:
    image: "redis:alpine"

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/$${GITTER_ID}

publish:
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc_products
    tag: latest
    when:
      branch: master
      
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc_products
    tag: $$TAG
    when:
      event: tag
