version: '2'
services:
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  catalogue_api:
    build: .
    volumes:
      - "./api:/home/app/api"
    ports:
      - "3010:3010"
    depends_on:
      - mongo
      - catalogue_worker
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    command: gulp api
  catalogue_worker:
    build: .
    volumes:
      - "./worker:/home/app/worker" 
    ports:
      - "3014:3014"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - DEBUG=ingester,scraper
    command: gulp worker
