version: '2'
services:
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  products_api:
    network_mode: host
    build: .
    ports:
      - "3011:3011"
    depends_on:
      - mongo
      - products_worker
    environment:
      - MONGO_HOST=localhost
      - REDIS_HOST=localhost
    command: gulp test:api
  products_worker:
    network_mode: host
    build: .
    ports:
      - "3015:3015"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=localhost
      - REDIS_HOST=localhost
    command: gulp test:worker
