version: '2'
services:
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - worker
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    command: gulp api
  worker:
    build: .
    ports:
      - "3004:3004"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - DEBUG=ingester
    command: gulp worker
