version: '2'
services:
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api:
    network_mode: host
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - worker
    environment:
      - MONGO_HOST=localhost
      - REDIS_HOST=localhost
    command: gulp test:api
  worker:
    network_mode: host
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=localhost
      - REDIS_HOST=localhost
    command: gulp test:worker
