version: '2'
services:
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  products_api:
    build: .
    ports:
      - "3010:3010"
    depends_on:
      - mongo
      - products_worker
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    command: gulp api
  products_worker:
    build: .
    ports:
      - "3014:3014"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - DEBUG=ingester
    command: gulp worker
